
/* Sending udp data */
CONN__ACQUIRE_MAC
CONN__UDP_SEND

/* Connecting with TCP */
CONN__ACQUIRE_MAC
CONN__TCP_SEND_SYN
CONN__RECEIVED_TCP_SYN_ACK
CONN__TCP_SEND_ACK

/* sending tcp data */
CONN__ACQUIRE_MAC
CONN__TCP_SEND_PUSH_ACK
CONN__TCP_RECEIVED_ACK
